"""empty message

Revision ID: 450c094cadc7
Revises: accb068ce0af
Create Date: 2019-05-19 15:43:38.206237

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '450c094cadc7'
down_revision = 'accb068ce0af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ih_area_info', sa.Column('updata_time', sa.DateTime(), nullable=True))
    op.drop_column('ih_area_info', 'updata_teime')
    op.add_column('ih_facility_info', sa.Column('updata_time', sa.DateTime(), nullable=True))
    op.drop_column('ih_facility_info', 'updata_teime')
    op.add_column('ih_house_image', sa.Column('updata_time', sa.DateTime(), nullable=True))
    op.drop_column('ih_house_image', 'updata_teime')
    op.add_column('ih_house_info', sa.Column('updata_time', sa.DateTime(), nullable=True))
    op.drop_column('ih_house_info', 'updata_teime')
    op.add_column('ih_order_info', sa.Column('updata_time', sa.DateTime(), nullable=True))
    op.drop_column('ih_order_info', 'updata_teime')
    op.add_column('ih_user_profile', sa.Column('updata_time', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'ih_user_profile', ['id_card'])
    op.drop_column('ih_user_profile', 'updata_teime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ih_user_profile', sa.Column('updata_teime', mysql.DATETIME(), nullable=True))
    op.drop_constraint(None, 'ih_user_profile', type_='unique')
    op.drop_column('ih_user_profile', 'updata_time')
    op.add_column('ih_order_info', sa.Column('updata_teime', mysql.DATETIME(), nullable=True))
    op.drop_column('ih_order_info', 'updata_time')
    op.add_column('ih_house_info', sa.Column('updata_teime', mysql.DATETIME(), nullable=True))
    op.drop_column('ih_house_info', 'updata_time')
    op.add_column('ih_house_image', sa.Column('updata_teime', mysql.DATETIME(), nullable=True))
    op.drop_column('ih_house_image', 'updata_time')
    op.add_column('ih_facility_info', sa.Column('updata_teime', mysql.DATETIME(), nullable=True))
    op.drop_column('ih_facility_info', 'updata_time')
    op.add_column('ih_area_info', sa.Column('updata_teime', mysql.DATETIME(), nullable=True))
    op.drop_column('ih_area_info', 'updata_time')
    # ### end Alembic commands ###
